DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (ID VARCHAR(50) NOT NULL, FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL);
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME) VALUES ('1', 'Spring','Boot');